//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AnalyticsEntities : DbContext
    {
        public AnalyticsEntities()
            : base("name=AnalyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SimpleSuitDocumentationList> SimpleSuitDocumentationLists { get; set; }
    
        public virtual ObjectResult<getSimplifiedProccesData_Result> getSimplifiedProccesData(Nullable<int> suitid)
        {
            var suitidParameter = suitid.HasValue ?
                new ObjectParameter("Suitid", suitid) :
                new ObjectParameter("Suitid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSimplifiedProccesData_Result>("getSimplifiedProccesData", suitidParameter);
        }
    }
}
